#!/usr/bin/env bash
# This script displays the content of the current directory,
# in a list format where only the part of the name
# after the first dash is displayed (refer to the example)
for files in *;
do
    echo "$files" | cut -d'-' -f2
done
