#!/usr/bin/env bash
# This script gives information about the holbertonschool file
i=holbertonschool
if [ -e $i ]
then
    echo "$i file exists"
    if [ -s $i ]
    then
	echo "$i file is not empty"
    else
	echo "$i file is empty"
    fi
    if [ -f $i ]
    then
	echo "$i is a regular file"
    fi
else
    echo "$i file does not exist"
fi
